# Generated by Django 3.2.8 on 2021-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='storeadmin',
            name='adress',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
