# Generated by Django 3.2.8 on 2021-10-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_auto_20211022_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
